[env:esp32-s3-devkitc-1-n16r8]
platform  = espressif32
board     = esp32-s3-devkitc-1
framework = espidf

; ---- Flash: 16MB ----
board_upload.flash_size = 16MB
board_build.flash_size  = 16MB

; ---- 自定义分区表（OTA 双 3MB 应用区）----
board_build.partitions  = partitions.csv

; ---- PSRAM: 8MB Octal (R8) ----
board_build.psram_type  = opi
board_build.flash_mode  = qio

; ---- 串口 ----
upload_speed   = 921600
monitor_speed  = 115200

build_flags =
    -DBOARD_HAS_PSRAM

    